version: "3.1"
services:
  web:
    build: .
    env_file:
      - .env.production
    ports:
      - "5000:5000"
    links:
      - "mongo:mongo"
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all"]
    volumes:
      - ./docker-cache/mongo:/data/db
    env_file:
      - .env.production
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    links:
      - "mongo:mongo"
    env_file:
      - .env.production
